# Generated by Django 5.2.5 on 2025-08-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_num', models.CharField(blank=True, help_text='filharmonické inventární číslo, pokud existuje', max_length=10, null=True, verbose_name='inventární číslo')),
                ('group', models.CharField(choices=[('smyčce', 'Smyčce'), ('dřeva', 'Dřeva'), ('žestě', 'Žestě'), ('bicí', 'Bicí'), ('harfy', 'Harfy'), ('klavíry', 'Klavíry'), ('elektronika', 'Elektronika')], help_text='Hlavní skupina nástrojů (např. smyčce, dřeva, žestě...)', max_length=14, verbose_name='Skupina')),
                ('subgroup', models.CharField(choices=[('housle', 'Housle'), ('violy', 'Violy'), ('violoncella', 'Violoncella'), ('kontrabasy', 'Kontrabasy'), ('smyčce ostatní', 'Ostatní (smyčce)'), ('flétny', 'Flétny'), ('hoboje', 'Hoboje'), ('klarinety', 'Klarinety'), ('fagoty', 'Fagoty'), ('dřeva ostatní', 'Ostatní (dřeva)'), ('lesní rohy', 'Lesní rohy'), ('trumpety', 'Trumpety'), ('trombony', 'Trombony'), ('tuby', 'Tuby'), ('žestě ostatní', 'Ostatní (žestě)'), ('bicí', 'Bicí'), ('bicí ostatní', 'Ostatní (bicí)'), ('harfy', 'Harfy'), ('harfy ostatní', 'Ostatní (harfy)'), ('klavíry', 'Klavíry'), ('klavíry ostatní', 'Ostatní (klavíry)'), ('klávesy', 'Klávesy'), ('elektronika ostatní', 'Ostatní (elektronika)')], help_text='Podskupina nástrojů podle zvolené skupiny', max_length=20, verbose_name='Podskupina')),
                ('subsubgroup', models.CharField(choices=[('smyčec', 'Smyčec'), ('nástroj', 'Nástroj'), ('příslušenství', 'Příslušenství'), ('obal', 'Obal')], help_text='Dílčí podskupina (např. smyčec – pouze pro smyčce; nástroj/příslušenství/obal – pro všechny skupiny)', max_length=14, verbose_name='Dílčí podskupina')),
                ('item', models.CharField(help_text='Co je to za nástroj?', max_length=24, verbose_name='Nástroj')),
                ('description', models.CharField(help_text='Výrobce, název, typ', max_length=24, verbose_name='Výrobce, název, typ')),
                ('serial_number', models.CharField(blank=True, help_text='Sériové číslo nástroje nebo příslušenství', max_length=12, null=True, verbose_name='Sériové číslo')),
            ],
        ),
        migrations.CreateModel(
            name='Disposals',
            fields=[
                ('id_disposals', models.AutoField(primary_key=True, serialize=False)),
                ('disposal_date', models.DateField(help_text='Datum, kdy byla položka zlikvidována', verbose_name='Datum likvidace')),
                ('disposal_reason', models.CharField(choices=[('vyřazení', 'Vyřazení'), ('poškození', 'Poškození'), ('ztráta', 'Ztráta'), ('odcizení', 'Odcizení'), ('prodej', 'Prodej'), ('jiné', 'Jiné')], help_text='Vyberte důvod, proč byla položka zlikvidována', max_length=10, verbose_name='Důvod likvidace')),
                ('notes', models.CharField(blank=True, help_text='Volitelná poznámka k likvidaci', max_length=24, verbose_name='Poznámka')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='instruments.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(help_text='Datum pořízení nástroje, povinné', verbose_name='Datum nákupu')),
                ('supplier', models.CharField(help_text='Dodavatel nástroje, povinné', max_length=24, verbose_name='Dodavatel')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Částka podle faktury, povinné', max_digits=12, verbose_name='Cena')),
                ('currency', models.CharField(help_text='Měna podle faktury, povinné', max_length=3, verbose_name='Měna')),
                ('invoice', models.CharField(help_text='Číslo faktury, povinné', max_length=12, verbose_name='Faktura')),
                ('notes', models.CharField(blank=True, help_text='Volitelná poznámka k nákupu', max_length=24, verbose_name='Poznámka')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='instruments.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id_rentals', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateField(help_text='Datum zápůjčky nebo vrácení', verbose_name='Datum akce')),
                ('rental_type', models.CharField(choices=[('loan', 'Zápůjčka'), ('return', 'Vrácení')], help_text='Zda jde o zápůjčku nebo vrácení', max_length=6, verbose_name='Typ akce')),
                ('renter_name', models.CharField(help_text='Osoba nebo organizace, které bylo půjčeno / od které vráceno', max_length=24, verbose_name='Jméno půjčitele')),
                ('notes', models.CharField(blank=True, help_text='Volitelná poznámka k akci', max_length=24, verbose_name='Poznámka')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='instruments.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id_servicing', models.AutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField(help_text='Datum servisu, povinné', verbose_name='Datum')),
                ('supplier', models.CharField(help_text='Dodavatel servisu, povinné', max_length=24, verbose_name='Dodavatel')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Částka podle faktury, pokud je neznámá, nech prázdné', max_digits=12, null=True, verbose_name='Cena')),
                ('currency', models.CharField(blank=True, help_text='Měna podle faktury, pokud je neznámá, nech prázdné', max_length=3, verbose_name='Měna')),
                ('invoice', models.CharField(blank=True, help_text='Číslo faktury, může být prázdné', max_length=12, verbose_name='Faktura')),
                ('notes', models.CharField(blank=True, help_text='Volitelná poznámka k servisu', max_length=24, verbose_name='Poznámka')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicings', to='instruments.inventory')),
            ],
        ),
    ]
