# Generated by Django 5.2.5 on 2025-09-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id_accessory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Příslušenství')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Příslušenství',
                'verbose_name_plural': 'Příslušenství',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id_manufacturer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Výrobce')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Země')),
            ],
            options={
                'verbose_name': 'Výrobce',
                'verbose_name_plural': 'Výrobci',
            },
        ),
        migrations.AlterModelOptions(
            name='disposals',
            options={'verbose_name': 'Likvidace', 'verbose_name_plural': 'Likvidace'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventář', 'verbose_name_plural': 'Inventáře'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Nákup', 'verbose_name_plural': 'Nákupy'},
        ),
        migrations.AlterModelOptions(
            name='rentals',
            options={'verbose_name': 'Zápůjčka', 'verbose_name_plural': 'Zápůjčky'},
        ),
        migrations.AlterModelOptions(
            name='servicing',
            options={'verbose_name': 'Servis', 'verbose_name_plural': 'Servisy'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='instruments', to='instruments.accessory', verbose_name='Příslušenství'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.manufacturer', verbose_name='Výrobce'),
        ),
    ]
