# Generated by Django 5.2.5 on 2025-09-14 10:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_accessory_manufacturer_alter_disposals_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentals',
            options={},
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='action_date',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='id_rentals',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='notes',
        ),
        migrations.AddField(
            model_name='rentals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='rentals',
            name='rental_date',
            field=models.DateField(default=datetime.date(2025, 9, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentals',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='group',
            field=models.CharField(choices=[('smyčce', 'Smyčce'), ('dřeva', 'Dřeva'), ('žestě', 'Žestě'), ('bicí', 'Bicí'), ('harfy', 'Harfy'), ('klavíry', 'Klavíry'), ('elektronika', 'Elektronika')], help_text='Hlavní skupina nástrojů', max_length=14, verbose_name='Skupina'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='subgroup',
            field=models.CharField(choices=[('housle', 'Housle'), ('violy', 'Violy'), ('violoncella', 'Violoncella'), ('kontrabasy', 'Kontrabasy'), ('smyčce ostatní', 'Ostatní (smyčce)'), ('flétny', 'Flétny'), ('hoboje', 'Hoboje'), ('klarinety', 'Klarinety'), ('fagoty', 'Fagoty'), ('dřeva ostatní', 'Ostatní (dřeva)'), ('lesní rohy', 'Lesní rohy'), ('trumpety', 'Trumpety'), ('trombony', 'Trombony'), ('tuby', 'Tuby'), ('žestě ostatní', 'Ostatní (žestě)'), ('bicí', 'Bicí'), ('bicí ostatní', 'Ostatní (bicí)'), ('harfy', 'Harfy'), ('harfy ostatní', 'Ostatní (harfy)'), ('klavíry', 'Klavíry'), ('klavíry ostatní', 'Ostatní (klavíry)'), ('klávesy', 'Klávesy'), ('elektronika ostatní', 'Ostatní (elektronika)')], help_text='Podskupina nástrojů', max_length=20, verbose_name='Podskupina'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='subsubgroup',
            field=models.CharField(choices=[('smyčec', 'Smyčec'), ('nástroj', 'Nástroj'), ('příslušenství', 'Příslušenství'), ('obal', 'Obal')], help_text='Dílčí podskupina', max_length=14, verbose_name='Dílčí podskupina'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_rentals', to='instruments.inventory'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='rental_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='renter_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_rentals', to='instruments.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
