# Generated by Django 5.2.5 on 2025-09-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Záznam logu', 'verbose_name_plural': 'Záznamy logů'},
        ),
    ]
